### ISSUE TITLE
Player Anchors

### ISSUE THREAD

**Issue by DuncanUszkay1** [DuncanUszkay1/Patchwork#70]
The largest piece missing of our core implementation is the ability to walk onto other servers and have your packets proxied to them. 

I'll list out some things I know we'll need to implement for this to work:
- [ ] Implement the outgoing translation layer service. We need to translate the packets that are being proxied to the peer since they could contain information only decipherable by us (the player's position on the patchwork mainly). Not sure where we should shove this in, it probably belongs in front of the messenger but that could be a huge hassle since we would need to change every call to the messenger with a call to the outgoing packet processor. Alternatively we could build the outgoing translation layer right into the messenger. Part of this task will be weighing the pros and cons of the different approaches
- [ ] Create a protocol for doing a border crossing login. The big question here is how much we need to differentiate these logins from client logins. I think it probably needs to be separate
- [ ] Delete the player entity as they walk across the border, and the other server will create them on the other side. This needs to look seamless.
- [ ] Create a re-entry procedure. This will be a different procedure to border crossing from the local server to a remote server, since we will want to disconnect any proxy connections they have and start interpreting their packets ourselves again
